### ISSUE TITLE
Use gpt-3.5-turbo-instruct

### ISSUE THREAD

**Issue by boromyr** [htadashi/GPT3-AHK#15]
How can I update the model from `text-davinci-edit-001` to `gpt-3.5-turbo-instruct`?
I have already modified:
```
MODEL_AUTOCOMPLETE_ID := "gpt-3.5-turbo-instruct"
url := "https://api.openai.com/v1/completions"
```
but I am not getting any response.

**Comment by htadashi** [comment]
Hi @boromyr, thanks for opening the issue. According to OpenAI [docs](https://platform.openai.com/docs/api-reference/completions#:~:text=Most%20models%20that%20support%20the%20legacy%20Completions%20endpoint%20will%20be%20shut%20off%20on%20January%204th%2C%202024.), "Most models that support the legacy Completions endpoint [will be shut off on January 4th, 2024](https://platform.openai.com/docs/deprecations/2023-07-06-gpt-and-embeddings)". 

I will change both edit/auto-complete functions to use the chat endpoints in the future.

**Comment by boromyr** [comment]
I tried version 0.3 but it doesn't work with gpt-3.5-turbo-instruct.
Also, line 4 should be `#SingleInstance force`,
line 87 should be: `body.messages := [{"role": "user", "content": UserInput . CutText}]` otherwise without `UserInput` no instruction will be sent.
Version 2 of cJson.ahk has been released, already tested with your code and it works.

**Comment by htadashi** [comment]
Thanks for your feedback and the heads up!

> I tried version 0.3 but it doesn't work with gpt-3.5-turbo-instruct.

Sorry, I initially misunderstood. I thought that gpt-3.5-turbo-instruct was going to be deprecated, but now I understood that it is running. It does not work because it uses a different API schema from gpt-3.5-turbo. Do you get better experience using gpt-3.5-turbo-instruct rather than gpt-3.5-turbo? If so, I will support it in the future.

> Also, line 4 should be #SingleInstance force,

According to [AHK docs](https://www.autohotkey.com/docs/v1/lib/_SingleInstance.htm), if force is omitted, it already defaults to Force.

> line 87 should be: body.messages := [{"role": "user", "content": UserInput . CutText}] otherwise without UserInput no instruction will be sent.

You are right. Thanks!

> Version 2 of cJson.ahk has been released, already tested with your code and it works.

Thanks for the information. As soon as I update the code to AHK 2.0, I will also update the third-party libraries.

**Comment by boromyr** [comment]
gpt-3.5-turbo-instruct has several advantages explained better here https://blog.nextideatech.com/openai-gpt-3-5-turbo-instruct/, including more coherent output and not being a chat, for example to translate selected text without getting as output `Certainly, here is the translated text: translated text`.
cJson also works with version 2 with GPT3-AHK v1.

**Comment by htadashi** [comment]
gpt-3.5-turbo-instruct is now compatible with the newer OpenAI scheme, so you only need to change the model in L64 of GPT3-AHK.ahk: https://github.com/htadashi/GPT3-AHK/blob/f9995797cf7e7cc060c65b50eab1f78545851b7c/GPT3-AHK.ahk#L64
