### ISSUE TITLE
The script doesn't work when I try to set temperature in request body

### ISSUE THREAD

**Issue by dino1729** [htadashi/GPT3-AHK#3]
I am trying to set the temperature of the response to 0.5 (instead of the default) by adding an additional line in the function:
body.temperature := 0.5 and it fails. The autocomplete will only output a space character. Is there a way to fix this?

**Comment by htadashi** [comment]
@dino1729 Thanks for your report.
I think I isolated the cause of the bug. The method `JSON.Dump` from [cJson](https://github.com/G33kDude/cJson.ahk) converts `0.5` to `"0.5"` but OpenAI server expects a float number instead of a string. I opened an issue there (https://github.com/G33kDude/cJson.ahk/issues/6) and will wait a fix to add the temperature parameter in the code.

**Comment by htadashi** [comment]
@dino1729 I've released a fix. You can change the temperature by changing the parameter `MODEL_AUTOCOMPLETE_TEMP` in [L13](https://github.com/htadashi/GPT3-AHK/blob/ca1e650c7014b966cb667db4a9ad1e81a024c4a0/GPT3-AHK.ahk#L13)
